network:
    version: 2
    wifis:
        renderer: networkd 
        wlan0:
            access-points:
                Airtel_dhar:
                    password: Air@123
            dhcp4: true 
            optional: true